### ISSUE TITLE
Thank YOU! 

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/openjdk-proposals#5]
I would like to let you you know how grateful I am.
Such researchs work are making the world a better place and Microsoft by investing in java is becoming an even bigger player in the open source world!

Side note: C# is I believe a historic accident because at the time the owners of Java® refused microsoft contributions, then Microsoft reacted by creating a better Java, C#. While C# is a *great* language I believe that jetbrains has achieved an even better Java (Kotlin) and most importantly the size of the ecosystem (Apache is valued at 20 Billions+$ of human resources). Hence Microsoft by contributing again to Java (now that it is truly open source and that Oracle is welcoming) make totally sense by investing into what is the biggest, most production ready software ecosystem on earth.
I'm *not* saying that Microsoft should diminish its investment in C# and that Kotlin totally obscolete it. But C# would be far more relevant if it got compatible with the JVM! If C# was ported on the JVM then we would have the best of both worlds. So I'm advocating for this, (and for investment into Kotlin (one can dream)) end of side note.

I am a noob in GC technology and you already talk about it in the Readme but I would like to state the obvious: collaborate and anticipate required changes and possible synergies with project loom. 

Finally, I see that Microsoft is porting the stack allocation optimization to both the JVM and coreclr / roslyn (a wonderful practice that I would like to see more). Now that Microsoft Edge contributes to chromium, I guess it would be a interesting addition to V8 to also implement to it stack allocation. 

Feel free to close this "issue" and thanks for the hard work :)

**Comment by karianna** [comment]
Thanks for the supporting comments - it's really appreciated by our team! :-)
